### ISSUE TITLE
event not show in safari

### ISSUE THREAD

**Issue by jipexu** [ka215/jquery.timeline#1]
https://ka215.github.io/jquery.timeline/index.html
can not see the event in the timeline ?...
Safari Version 10.1.1 (12603.2.4)

**Comment by ka215** [comment]
Thank you for the report.
In Safari, there was a problem that when a Date object had a dash, it did not return a valid datetime. Revised version 1.0.2 has been released.

**Comment by jipexu** [comment]
ah better now ! thanks i will investigate more this nice work !

**Comment by ka215** [comment]
Closed because it has already been processed this issue.
