### ISSUE TITLE
Can't understand -1 in Line 1109 for calculating the end date of the timeline

### ISSUE THREAD

**Issue by s890081tonyhsu** [ka215/jquery.timeline#12]
In line 1103, you've told me that you want to count the end date of the timeline.

But on the month case([Line 1109](https://github.com/ka215/jquery.timeline/blob/master/src/timeline.js#L1109)), I can't understand that you want to subtract 1 after adding the range.

That cause me a bug as follow, you can see that the events will stop at the end of the September.

The top two events' end date is 2222-12-31(We wanted to make it looks like infinity, so we set that date).

The bottom four events' end date is 2017-10-01, so we expect that the bars will reach the first day of October.

![default](https://user-images.githubusercontent.com/3825000/30239325-c0164e66-958c-11e7-85a1-ee628f605c5c.png)

When I delete that '-1' code, it will act what I need. So I'm a little curious about why you wanted to do that.

Sincerely,

OtomeSound

**Comment by ka215** [comment]
Hi,
I'm sorry for my late reply.

Sure, as you said, I also looked like a bug.
I will investigate and respond asap.
