### ISSUE TITLE
Hours off by one issue

### ISSUE THREAD

**Issue by mattgallivan** [ka215/jquery.timeline#14]
Using Strings such as

```
"end" : "2017-06-08 15:30:00+00:00",
"start" : "2017-06-08 10:15:00+00:00"
```
is displaying events at
```
"end" : "2017-06-08 16:30:00+00:00",
"start" : "2017-06-08 11:15:00+00:00"
```

I think this might be a timezone issue?

**Comment by ka215** [comment]
Sorry for my late reply.

It may be a matter of timezone, but I'll investigate. If it's a problem, I'll fix it, please wait.
