### ISSUE TITLE
Set date-time range

### ISSUE THREAD

**Issue by gab88** [ka215/jquery.timeline#15]
Hi,

Is there a proper way of setting the start and end date-time range on the timeline?
Now I use the combinations of scale, startDatetime, range options but it would be awesome if the start and end dates could be set dynamically in the browser page, where the tool is included.
It's already a great tool and easy to use.

Thanks for your answer in advance,
Gab

**Comment by ka215** [comment]
Hi,

Specifically, how do you dynamically want the date and time of the timeline to be set?

Thanks,

**Comment by gab88** [comment]
If example if you click on the calendar icon at the top of the page where the dates are shown (in example 1. is Sun, 28 May ~ Tue, 30 May) a popup or some text fields or something would be great. How can you set the mentioned dates to something else to see other parts of the timeline without editing code?

Thanks,
Gab
