### ISSUE TITLE
Relation lines do not draw correctly if minGridSize is anything other than 30

### ISSUE THREAD

**Issue by BenEllery** [ka215/jquery.timeline#18]
Specifically, horizontal positioning is incorrect. Line is positioned too far left if minGridSize is less than 30, and too far right if minGridSize is greater than 30.

**Comment by xsequeira** [comment]
True. Also checked it and if the value is !30, the lines are out of location.

**Comment by xsequeira** [comment]
Also checked if minGridSize is 30 and the minGridPer is greater than 2, the lines disappear.
