### ISSUE TITLE
Multiple timelines on single page and rangeAlign to eventId

### ISSUE THREAD

**Issue by nalvesubi** [ka215/jquery.timeline#19]
If we use two timelines on a single page the first one renders correctly but the second one renders with the following problems:
- The pointer doesn't show up;
- rangeAlign set to current doesn't work (the timeline defaults to left alignment);
- Previous and next arrows shows in the bottom of the timeline instead of the middle;
When we try to use rangeAlign to eventId the timeline defaults to current, is there a way to align the timeline to an eventId or to the first timeline element by default?
Thanks

**Comment by SamToorchi** [comment]
same problem hier!

**Comment by ka215** [comment]
This issue has been resolved in version 2.x and later.
