### ISSUE TITLE
Zoom in ?

### ISSUE THREAD

**Issue by vbenner** [ka215/jquery.timeline#22]
Hello,

I'm trying to implement the timeline to monitor events with small time differences.
For exemple, I may have such a sequence.

I tried to modify .css but it doesn't fit.

Thank you,

Vincent / From France

        <li data-timeline-node="{ row:1, start:'2018-01-24 09:00:00',end:'2018-01-24 09:00:00',content:'' }"></li>
        <li data-timeline-node="{ row:1, start:'2018-01-24 09:00:02',end:'2018-01-24 09:00:02',content:'' }"></li>
        <li data-timeline-node="{ row:1, start:'2018-01-24 09:00:46',end:'2018-01-24 09:00:46',content:'' }"></li>
        <li data-timeline-node="{ row:1, start:'2018-01-24 09:00:55',end:'2018-01-24 09:00:55',content:'' }"></li>
        <li data-timeline-node="{ row:1, start:'2018-01-24 09:01:04',end:'2018-01-24 09:01:04',content:'' }"></li>
        <li data-timeline-node="{ row:1, start:'2018-01-24 09:01:23',end:'2018-01-24 09:01:23',content:'' }"></li>
        <li data-timeline-node="{ row:1, start:'2018-01-24 09:01:39',end:'2018-01-24 09:01:39',content:'' }"></li>
        <li data-timeline-node="{ row:1, start:'2018-01-24 09:01:48',end:'2018-01-24 09:01:48',content:'' }"></li>

**Comment by ka215** [comment]
It was supported the feature of zoom at version 2.x.
You should enable the zoom option on that version as below:

```js
$('#my-timeline').Timeline({
  zoom: true
});
```

Please try to use that version.

**Comment by rkorzeniewski** [comment]
@ka215 if I understand how this feature is working then it changes the scale factor only, so you can "zoom in" from days to hours but nothing between, right?
