### ISSUE TITLE
Issues in Options:  showHeadline & httpLnaguage 

### ISSUE THREAD

**Issue by SirYmp** [ka215/jquery.timeline#24]
showHeadline is always showing the Headline, independently of the option passed.

There's a typo in the options that may create some confusion/issues, regarding language setup:  httpLnaguage.

**Comment by ka215** [comment]
I hope you will use version 2.x because that has fixed any troubles of version 1.x.

**Comment by SirYmp** [comment]
Sure will!
Despite those problems I implemented version 1.x  in our solution.
As soon as you have the documentation up, I will migrate to the new version, because I see some opportunities to improve our solution.
