### ISSUE TITLE
Unable to add new event. Cannot read property 'push' of undefined.

### ISSUE THREAD

**Issue by Rahul-RB** [ka215/jquery.timeline#26]
Following the README, I am unable to add events via 

    `$("#myTimeline).timeline(

        "addEvent",

        [{startDate:..}],

        function(){}
    );`

Could you at least show an example for the same?

**Comment by Rahul-RB** [comment]
Following the README, I am unable to add events via 

    `$("#myTimeline).timeline(

        "addEvent",

        [{startDate:..}],

        function(){}
    );`

Could you at least show an example for the same?

**Comment by ka215** [comment]
I hope you will use version 2.x because that has fixed any troubles of version 1.x.

**Comment by Rahul-RB** [comment]
Ahh okay, 2.x is now available. Thank you for the prompt update! :smile:
