### ISSUE TITLE
Donating

### ISSUE THREAD

**Issue by AntonFix** [ka215/jquery.timeline#29]
Hi,
I cant to donate (from card and from PayPal wallet):
https://i.imgur.com/Z5nK9lR.png

Do you have another methods to pay?

**Comment by ka215** [comment]
I'm very sorry.

The paypal api implemented on donation page was old.
Then I replaced that to new api.

Please try it one more from [here](https://ka215.github.io/jquery.timeline/donation.html).

**Comment by AntonFix** [comment]
Yes, i did it.
Buy some coffee ;)

Thnx for Timeline!

**Comment by ka215** [comment]
Thank you for making a contribution!
