### ISSUE TITLE
zoom in and zoom out in v1

### ISSUE THREAD

**Issue by SamToorchi** [ka215/jquery.timeline#32]
function to create zoom in and zoom out

HTML:
`<button id="one" type="button" value="4">zoom in</button>
<button id="two" type="button" value="4">zoom out</button>`

Script:
` $('#one').click(function() { ab+=4; $("#myTimeline").timeline('render', {minGridPer:ab}); });
$('#two').click(function() {
 ab-=4;
 $("#myTimeline").timeline('render', {minGridPer:ab});
 }); `

**Comment by ka215** [comment]
The zoom function has been implemented in version 2.x and later.
