### ISSUE TITLE
Issue with a particular day

### ISSUE THREAD

**Issue by potimaripoti** [ka215/jquery.timeline#35]
With the grid set up with months and days the 27th October is taking 2 days of the grid and pushing a day all the events afterwards.

[https://imgur.com/a/lcie3r6](url)

Thanks

**Comment by ka215** [comment]
Hi there,

I could not reproduce the same trouble as you. Would you tell me the option values of the plugin that had set when you encountered the trouble?
Also, please let me know the timezone of your execution environment. Does summer-time exist in your locale? Unfortunately, the current plugin does not support daylight savings time, which may be the cause.

Thank you,

**Comment by potimaripoti** [comment]
Hi, 
Thanks for the quick response. I posted below the script I'm using, I'm not specifying any timezone in particular, I'm in London timezone. Do I need it? Thanks you.

    <script>
        let options_1 = {
            type: 'bar',
            rangeAlign: 'left',
            width: 'auto',
            height: 'auto',
            minGridSize: 75,
            marginHeight: 2,
            startDatetime: '2019-05-22 00:00',
            endDatetime: '2020-01-22 00:00',
            scale: 'day',

            headline: {
                display: true,
                title: 'Course Calendar',
                range: false,
                color: '#2A3F54'
            },
            sidebar: {
                sticky: true,
                overlay: false,
                list: [
                    '<p class="text-center"><strong>Course Calendar</strong></p>',
                    '<p class="text-center"><strong></strong></p>',
                    '<p class="text-center"><strong>C Events</strong></p>',
                    '<p class="text-center"><strong>K Events</strong></p>',
                ]
            },
            ruler: {
                top: {
                    lines: ['month', 'day', 'weekday'],
                    height: 50,
                    fontSize: 14,
                    color: '#2A3F54',
                    background: '#ffffff',
                    format: { year:'numeric', month: 'long', day: 'numeric', weekday: 'short' }
                },
                
            },


        }
        $('#myTimeline').Timeline(options_1)
    </script>

**Comment by ka215** [comment]
Hi,
Thank you for providing information, I could reproduce the trouble you reported.
I'm looking like in all probability the cause of the trouble is the difference in time due to the end of summertime on 10/27.

The current plugin doesn't support summertime (Daylight Savings Time) or timezone offsets, so I'm going to do that.

Sorry, I hope to wait until my corresponding is over.

**Comment by ka215** [comment]
Oh and,
as a temporary response method at the present time, by including the summertime start date in the timeline display range, the summertime difference can be offset so that normal display can be performed.

Thank you,

**Comment by ka215** [comment]
This issue has already been resolved.
