### ISSUE TITLE
Available on npm?

### ISSUE THREAD

**Issue by ole1986** [ka215/jquery.timeline#36]
I have seen the package.json but could not find it on npmjs.com
Is there any chance to make this downloadable through npm?

**Comment by ka215** [comment]
Yes, I'm going to register next published stable 2.0.0 version to the npm and the bower.
I hope you wait for releasing next.

**Comment by ka215** [comment]
I've registered this package to the npm and the bower. And the package name was changed to the "**jq-timeline**". We can install since using `npm i jq-timeline`.
