### ISSUE TITLE
npm: npm i jquery-timeline

### ISSUE THREAD

**Issue by danycr90** [ka215/jquery.timeline#40]
Hi dear @ka215, how are you?

I'm trying to use the plugin as a module in my project, but when I execute the command (npm i jquery-timeline), that operation download another plugin, not yours, do you knew about it?

This is the plugin that it command download
https://github.com/d-ashesss/jquery-timeline

Have a nice day,
Regards.

**Comment by ka215** [comment]
Hi there,

I do not register this plugin to the npm repository yet. I'm going to register that when I will release the stable version 2.0.0, because at this version has some bugs.

The library you downloaded with `npm i jquery-timeline` is not made one by me.
Please clone from this github repository currently.

Thank you,

**Comment by danycr90** [comment]
Hi dear @ka215:

Thanks for your reply. I wrote you to let you know about there is already another registered with that name. I notice that you have in (**Quick start**) this option **npm i jquery-timeline**, and this name is used by https://github.com/d-ashesss/jquery-timeline.

I know you have a lot of work, this is only a documentation detail,

Have a nice day,
Regards.

**Comment by danycr90** [comment]
Hi dear @ka215:

Thanks for your reply. I wrote you to let you know about there is already another registered with that name. I notice that you have in (**Quick start**) this option **npm i jquery-timeline**, and this name is used by https://github.com/d-ashesss/jquery-timeline.

I know you have a lot of work, this is only a documentation detail,

![Home   jQuery Timeline](https://user-images.githubusercontent.com/38047803/60828035-d8b66600-a187-11e9-866f-7989fc95d8c4.png)

Have a nice day,
Regards.

**Comment by ka215** [comment]
Hi, @danycr90

Thank you for telling me, and I'm sorry to be outputting misleading notation on the documentation.
I'm going to publish a stable version when I have tested the latest beta 2 released today.
At that same time, I'm going to register with npm and bower.

best regards,

**Comment by ka215** [comment]
Supported the npm install and bower install.
