### ISSUE TITLE
TypeError: t.resolve is not a function

### ISSUE THREAD

**Issue by rodrigoGA** [ka215/jquery.timeline#41]
I am having problems to incorporate your library into a project made with ionic 3.
I receive the following error: ` TypeError: t.resolve is not a function`.

apparently the problem is with polyfills

`r@http://localhost:8000/build/polyfills.js:3:7745 F</l</t.prototype.scheduleTask@http://localhost:8000/build/polyfills.js:3:15480 F</c</r.prototype.scheduleTask@http://localhost:8000/build/polyfills.js:3:11405 F</c</r.prototype.scheduleMicroTask@http://localhost:8000/build/polyfills.js:3:11657 f@http://localhost:8000/build/polyfills.js:3:20198 x</t.prototype.then@http://localhost:8000/build/polyfills.js:3:22554 setDriver@http://localhost:8000/build/vendor.js:239315:44 LocalForage@http://localhost:8000/build/vendor.js:239104:14 [4]<@http://localhost:8000/build/vendor.js:239377:22 s@http://localhost:8000/build/vendor.js:236592:584 e@http://localhost:8000/build/vendor.js:236592:755 @http://localhost:8000/build/vendor.js:236592:773 @http://localhost:8000/build/vendor.js:236592:38 @http://localhost:8000/build/vendor.js:236592:277 @http://localhost:8000/build/vendor.js:239384:30 __webpack_require__@http://localhost:8000/build/vendor.js:55:30 @http://localhost:8000/build/vendor.js:236114:70 __webpack_require__@http://localhost:8000/build/vendor.js:55:30 604@http://localhost:8000/build/main.js:4059:74 __webpack_require__@http://localhost:8000/build/vendor.js:55:30 599@http://localhost:8000/build/main.js:4016:70 __webpack_require__@http://localhost:8000/build/vendor.js:55:30 webpackJsonpCallback@http://localhost:8000/build/vendor.js:26:23 @http://localhost:8000/build/main.js:1:1 `

**Comment by rodrigoGA** [comment]
The problem is with minimized library, with the source it works well

**Comment by ka215** [comment]
Hi there,

In this plugin since version 2.0.0 beta 2, there is using the core-js instead of the "babel/polyfill" that is departed. Then, by setting "usage" to "useBuiltIns" option, it will be imported polyfill to the source code only when needs to polyfill.
I thought that probably needs full polyfill when uses on the ionic. If you want to transpile with full polyfill, you should try to deploy after modifying below.

.babelrc:
```json
  presets: [
    [
      "@babel/preset-env",
      {
        useBuiltIns: "entry",
        corejs: 3
      }
    ]
  ],
```

src/timeline.js:
```js
import "core-js/stable";
import "regenerator-runtime/runtime";
/*!
 * jQuery Timeline
 * ------------------------
```

Then you should run deploy at `npx gulp prod`.

Best regards,
