### ISSUE TITLE
Label for each point

### ISSUE THREAD

**Issue by AnotherUsernameToRemember** [ka215/jquery.timeline#47]
Hello,

Is there any way to add labels for each point? Have added a screenshot to show what I am trying to achieve. Is this feasible and if so, what configurations do I need to choose to create it?

Thank you.
![2019-08-26 10_24_51-ProductCenter ODA](https://user-images.githubusercontent.com/54542351/63698441-d9b15e80-c7ec-11e9-8572-07270b91b9b8.png)

**Comment by ka215** [comment]
Hi there,

Do you want as like as tooltip or popover of bootstrap? Then you can.

However, there is not able to realize in currently features as you shown an image.

Thank you,
