### ISSUE TITLE
Wrong year displayed in header

### ISSUE THREAD

**Issue by Flemmingc** [ka215/jquery.timeline#48]
When displaying the year on the top ruler the value is one year less then the data. The bottom ruler displays the correct year. 
By using the browser debugger, you can see that the "year-2018" element has the value "2017".

![Timeline Ruler wrong - Html](https://user-images.githubusercontent.com/56384622/66548927-80a24d80-eb42-11e9-838c-3e68f9d910eb.PNG)

**Comment by ka215** [comment]
Hi there,

Thank you for telling me that.
I'll fix it asap.

**Comment by Flemmingc** [comment]
It seems to be related to the specification of the format. 
If you specify Year : "short" then the year is displayed correct, 
but if you specify Year:"numeric", it is displayed wrong

**Comment by ka215** [comment]
Thank you for information.

I've fixed that displayed years on the ruler at new version.

**Comment by Flemmingc** [comment]
Great, thank you.
