### ISSUE TITLE
addEvent causes entire timeline refresh

### ISSUE THREAD

**Issue by paraleadogg** [ka215/jquery.timeline#51]
Hey - just a quick one

I've noticed when trying to add events using addEvent it causes the entire timeline to flash as the timeline is reloaded/refreshed

Is there a nicer or cleaner way to do this?

I'm currently pushing items onto an existing timeline instance like this (with items being an array of bar objects)

`$('#timeline').Timeline('addEvent', items);`

This causes the timeline to blink as the entire thing is reloaded - I'm looking to push items on as and when they become available so the blinking isn't great from a user perspective (as i may ad an item every few seconds or so)

Any ideas?

**Comment by paraleadogg** [comment]
Aaah after posing I realised this was simply a css effect (applied to the show and shown states)

Simply overriding the .jqtl-events style to always have opacity:1 sorted the issue

**Comment by ka215** [comment]
Thank you, nice to solve!

**Comment by ka215** [comment]
Fixed this issue in version 2.1.0.
