### ISSUE TITLE
Getting syntax error on line 1089

### ISSUE THREAD

**Issue by pmilbr** [ka215/jquery.timeline#6]
I'm likely doing something wrong but I keep getting a syntax error on line 1089 in timeline.js...
![image](https://user-images.githubusercontent.com/29458893/27384546-3ae3e82a-565d-11e7-803f-80059d3c060c.png)

Any suggestions?

**Comment by ka215** [comment]
Please modify line 1089 as follows:
```
eventNodes  = JSON.parse( data.timeline.text() ),
```
If the error still persists, insert the following debug code at line 1087 and tell me the log. Perhaps the string in JSON format may be corrupted because it is not properly escaped.
```
console.log( $(obj).data('timeline').timeline.text() );
```

**Comment by pmilbr** [comment]
Thanks for the quick reply.  I changed my code around a bit since yesterday and I'm not currently getting that error.  I believe it might have been related to creating the timeline with a date that wasn't formatted properly, but I can't currently re-create the error.  
I will be doing some more work with it today, so if I run into the issue again, I will try try the steps you recommended.
