### ISSUE TITLE
help.nothing appear correct

### ISSUE THREAD

**Issue by ali-ghazi78** [ka215/jquery.timeline#60]
hello .
tnx for your really nice plugin 
when i use your plugin i get this result
![image](https://user-images.githubusercontent.com/39215015/89871277-686ce600-dbcc-11ea-9bc5-6f1875d3ccb3.png)
this is my code
`

[index2.txt](https://github.com/ka215/jquery.timeline/files/5055549/index2.txt)

`

thank you.

**Comment by ka215** [comment]
Hi, there was a mistake in your HTML markup.

You need to markup the element (`<div id="my-timeline"></div>`) of the container where the timeline is displayed inside the body tag.
