### ISSUE TITLE
Rulers locale and and custom options bug

### ISSUE THREAD

**Issue by menjic** [ka215/jquery.timeline#61]
Top and bottom rulers are configured with identical options: 

_**// displays ruler
            ruler: {
                bottom: {
                    lines: ["year", "month"],
                    locale: "sr-Latn-RS",
                    format: { custom: "%Y%m" }
                },
                top: {
                    lines: ["year", "month"],
                    locale: "sr-Latn-RS",
                    format: { custom: "%Y%m" }
                }
            },**_

Bottom ruler shows correctly, year line is 4 digit year and month line is two digit month,

Top ruler has a bug, it shows year row with month included in my case 1.1.2020. because of locale but changing locale just changes format for example US gives you year like 1/1/2020. 

Months line is displayed in my case like 1.8. but if you inspect code you can see value 1.8.2020. so it is whole year, day and month for both year line and month line.

Additionally bottom ruler has bug with locale, setting the locale has influence only on top ruler, not the bottom, what ever you set in options only top ruler is changing bottom stays in this default format, year line is 4 digit year month line is two digit month.

Screenshot is attached for better understanding:

![jqtl](https://user-images.githubusercontent.com/66558126/90334388-9b98e600-dfcd-11ea-9472-7892da08c766.JPG)

**Comment by ka215** [comment]
Fixed this issue in version 2.1.0.
