### ISSUE TITLE
Relation line is not shown in Chrome

### ISSUE THREAD

**Issue by fdj184** [ka215/jquery.timeline#7]
Hi, I found your timeline project today, thanks for sharing this and the easy-understanding document.
So here is my problem, I can display relation lines in IE (version: 11.0.9600.18738), but not in Chrome (version: 60.0.3112.78). Is there something wrong?

**Comment by ka215** [comment]
Hi there,
In my Chrome version 60.0.3112.78 (the same version as you) the relationship line is displayed. Will not it appear on the demo page below?

https://ka215.github.io/jquery.timeline/index2.html

If the relation line of the demo page is displayed, there may be a mistake in the definition of the relation line in your JavaScript.

**Comment by fdj184** [comment]
well .. I can see the relation lines in your demo page. 
I'll try to figure out what's wrong in my code, thanks for your help.

**Comment by ka215** [comment]
Ok,
So please tell me about JavaScript for plugin when you can not see the relationship line.

**Comment by robogen** [comment]
I have a similar issue, can see relation line in your demo but not in my code. I'll try to report back if I can figure out why
