### ISSUE TITLE
Request: Can LimitScaleGrids be overridden in config?

### ISSUE THREAD

**Issue by MrXavierLin** [ka215/jquery.timeline#71]
For example, when using scale at hour level, sometime we need to extend the limit from 720(30 days) to 744(31 days ), we have to hard code the source code to achieve this.

**Comment by ka215** [comment]
Hi there,

Unfortunately, we can not override the LimitScaleGrids on other than the rebuilding after source code modification.

If the grid is drawn close to the limit with the browser of a device that equipped with generally memory size, there is a high possibility that the memory will be exhausted in the timeline display and the browser will crash. Therefore, this plugin has a limit on the number of grids.
Perhaps rendering with more than 700 grids cannot guarantee the plugin to work properly.

Thank you,

**Comment by ka215** [comment]
Added disableLimitter option in version 2.1.2 to avoid LimitScaleGrids validation.

See [the release notes](https://github.com/ka215/jquery.timeline/releases/tag/v2.1.2) for details.

**Comment by MrXavierLin** [comment]
Thank you, that is a very nice option
