### ISSUE TITLE
Sources of examples

### ISSUE THREAD

**Issue by friedrico** [ka215/jquery.timeline#75]
https://ka215.github.io/jquery.timeline/

Would you please provide the sources for the example charts?

**Comment by ka215** [comment]
So I'd like to introduce the sources of several sample pages that published as the demo.

* [Demo-1: as early type of scheduler type](https://gist.github.com/ka215/ec56aa06928adadb93c3662806c98e98)
* [Demo-2: MARVEL Cinematic Universe History as demo of jQuery.Timeline](https://gist.github.com/ka215/50b7d4d61ff2316dd1c1783b1c98de9f)
* [Demo-3: source of `https://ka2.org/jqtl-v2/v2.1.html`](https://gist.github.com/ka215/5ce08eeac67c897828de7c367cbd782f)

I hope this is helpful to you.

**Comment by friedrico** [comment]
Thanks that is very helpful.
Follow up questions:
 - For my task it is necessary that the labels are always shown - the width of events without end date is 0, so how would you realise that?
 - is it possible to generate a dotted vertical line from the event to the ruler? The idea is that the events would be far larger if the labels are shown always and in order to keep track of the actual point of time, such vertical lines would be useful.
Do you think this can easily be achieved?

**Comment by ka215** [comment]
> For my task it is necessary that the labels are always shown - the width of events without end date is 0, so how would you realise that?

Use the `type: 'mixed'` option to initialize the timeline. Now the events with an end of 0 will be displayed as pointer events. You can then add extended attributes to the events you want to label and style them to achieve this.
Please refer to below sample.

<https://ka2.org/jqtl-v2/sample-sticky-label.html>

> is it possible to generate a dotted vertical line from the event to the ruler? The idea is that the events would be far larger if the labels are shown always and in order to keep track of the actual point of time, such vertical lines would be useful.
Do you think this can easily be achieved?

I find the sample 1 of the following pages useful.

<https://ka2.org/jqtl/jquery-timeline-samples>

Thank you,
