### ISSUE TITLE
how i can create smaller time scale like (seconds) 

### ISSUE THREAD

**Issue by salamaashoush** [ka215/jquery.timeline#8]
i working on an app for tracking small time scales (seconds) and i found your plugin and it is really awesome ,but the problem is my event is overlapped on each others because ( as i imagine time deference between them is seconds)
![screenshot](http://i.imgur.com/E7iAYQZ.png)

**Comment by ka215** [comment]
If events overlap due to the neary times, try using "row" as event parameter to make the lines displayed different. Thanks,

**Comment by salamaashoush** [comment]
i tried to implement it but i failed , i will be grateful if you can take a look at my code maybe you can figure out what is wrong with it 
[https://github.com/salamaashoush/jquery.timeline/blob/master/src/timeline.js](https://github.com/salamaashoush/jquery.timeline/blob/master/src/timeline.js)

**Comment by henryalps** [comment]
@salamaashoush I also working on a project which needs time scaled in minute 😺 wonder if you have found any solution?

**Comment by SamToorchi** [comment]
still open! 
minuteIntervale doesn't work 😢

**Comment by ka215** [comment]
Hi there,

Unfortunately since version 2.x of this plugin, The "minuteInterval" option has been departed. Instead of that option, We hope you should be specified "quarterHour" or "halfHour" at the "scale" option.

Thank you,
