### ISSUE TITLE
Unable to see BS popover

### ISSUE THREAD

**Issue by mario20** [ka215/jquery.timeline#9]
I don't see the popover in the demo and can't get it to work on my local set up.

**Comment by ka215** [comment]
Certainly, you are right.
The cause seems to be an unbound bug because there is no DOM node trying to bind a bootstrap popover before the timeline event is rendered.
I'm planning on adding a method that allows custom callbacks to be defined immediately after timeline events are rendered.
Please wait till the release, thank you.

**Comment by mario20** [comment]
@ka215,

Thanks for the quick response. I'll look forward to the update. 
Here's my quick fix for prototype purpose:
$( window ).scroll(function() {
        $('.timeline-node').popover('show')
        $('.timeline-node').each(function(){
            console.log('temp');
            if ( $(this).data('toggle') === 'popover' ) {
                $(this).attr( 'title', $(this).text() );
                $(this).popover({
                  trigger: 'hover'
                });
            }
        });
    });

It's not super elegant, but it does the job. Also restyled to fit our project's theme. 
![screen shot 2017-09-04 at 11 04 37 am](https://user-images.githubusercontent.com/2170955/30033453-04782852-9161-11e7-97c3-876fe1e4ff2b.png)

**Comment by ka215** [comment]
@mario20,

I released version 1.0.5 that added handling event of afterRender. In that version, you can enable bootstrap's popover by coding as follow: 

```javascript
$("#myTimeline").on('afterRender.timeline', function(){
    // usage bootstrap's popover
    $('.timeline-node').each(function(){
      if ( $(this).data('toggle') === 'popover' ) {
        $(this).attr( 'title', $(this).text() );
        $(this).popover({
          trigger: 'hover'
        });
      }
    });
  });
```

Please try it.

P.S.
For some reason, because Github Pages is not updated, We can not check the popover on the demo page...

**Comment by ka215** [comment]
Closed because it has already been processed this issue.

**Comment by mario20** [comment]
Thanks for the update @ka215 . We'll implement and let you know how it goes.
